import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import articlesRouter from "./articles";
import categoriesRouter from "./categories";
import commentsRouter from "./comments";
import adminCommentsRouter from "./adminComments";
import adminStatsRouter from "./adminStats";
import adminUsersRouter from "./adminUsers";
import settingsRouter from "./settings";
import uploadRouter from "./upload";
import adminImportRouter from "./adminImport";
import adminMigrateImagesRouter from "./adminMigrateImages";
import proxyImageRouter from "./proxyImage";
import tipoCambioRouter from "./tipoCambio";
import climaRouter from "./clima";
import adminNacionalRouter from "./adminNacional";
import subscribeRouter from "./subscribe";
import adminEditorsRouter from "./adminEditors";
import adminReviewRouter from "./adminReview";
import notificationsRouter from "./notifications";
import revisionsRouter from "./revisions";
import sitemapRouter from "./sitemap";
import auditRouter from "./audit";
import adminViewsChartRouter from "./adminViewsChart";
import contactRouter from "./contact";
import dailyBriefingRouter from "./dailyBriefing";
import externalNewsRouter from "./externalNews";
import cronRouter from "./cron";
import summarizeRouter from "./summarize";
import trendsRouter from "./trends";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(articlesRouter);
router.use(categoriesRouter);
router.use(commentsRouter);
router.use(adminCommentsRouter);
router.use(adminStatsRouter);
router.use(adminUsersRouter);
router.use(settingsRouter);
router.use(uploadRouter);
router.use(adminImportRouter);
router.use(adminMigrateImagesRouter);
router.use(proxyImageRouter);
router.use(tipoCambioRouter);
router.use(climaRouter);
router.use(adminNacionalRouter);
router.use(subscribeRouter);
router.use(adminEditorsRouter);
router.use(adminReviewRouter);
router.use(notificationsRouter);
router.use(revisionsRouter);
router.use(sitemapRouter);
router.use(auditRouter);
router.use(adminViewsChartRouter);
router.use(contactRouter);
router.use(dailyBriefingRouter);
router.use(externalNewsRouter);
router.use(cronRouter);
router.use(summarizeRouter);
router.use(trendsRouter);

export default router;
